USE ayres_ssb_dashboard;

CREATE TABLE age_groups (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  ssb_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(50) NOT NULL,
  min_age INT UNSIGNED NOT NULL,
  max_age INT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_age_groups_ssb_id (ssb_id),
  CONSTRAINT fk_age_groups_ssb
    FOREIGN KEY (ssb_id) REFERENCES ssb (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

ALTER TABLE participants ADD COLUMN photo VARCHAR(255) DEFAULT NULL AFTER nickname;
